In [1]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [5]:
np.full((4,4),114)

array([[114, 114, 114, 114],
       [114, 114, 114, 114],
       [114, 114, 114, 114],
       [114, 114, 114, 114]])

In [9]:
a = np.random.rand(4,4)
np.linalg.det(a)

0.018423089197078753